### ISSUE TITLE
Blockscout couldn't retrieve big transaction batches

### ISSUE THREAD

**Issue by DmytroNazarenko** [skalenetwork/blockscout#33]
Blockscout couldn't retrieve big transaction batches (250 getTransactionReceipt in 1 batch) when sChain has a lot of txs in blocks.
Failed with error:
```
** (FunctionClauseError) no function clause matching in EthereumJSONRPC.HTTP.standardize_response/1
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/http.ex:135: EthereumJSONRPC.HTTP.standardize_response(%{"error" => "Bad JSON RPC request: [{\"id\":249,\"jsonrpc\":\"2.0\",\"method\":\"eth_getTransactionReceipt\",\"params\":[\"0xd874a7b29f2963be595b15c93c9358d3b9acf9070960d5143547ef5d2667b63e\"]},{\"id\":248,\"jsonrpc\":\"2.0\",\"method\":\"eth_getTransactionReceipt\",\"params\":[\"0xadb21bad6e892a0eb350a8a660ecedab8b913e530a5392827f50281bca72458c\"]},
    ....
{\"id\":221,\"jsonrpc\":\"2.0\",\"method\":\"eth_g" <> ..., "id" => "0xBADF00D"})
    (elixir 1.12.3) lib/enum.ex:1582: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/http.ex:44: EthereumJSONRPC.HTTP.chunked_json_rpc/3
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/request_coordinator.ex:86: anonymous fn/3 in EthereumJSONRPC.RequestCoordinator.perform/4
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/request_coordinator.ex:106: EthereumJSONRPC.RequestCoordinator.trace_request/2
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/receipts.ex:136: EthereumJSONRPC.Receipts.fetch/2
    (elixir 1.12.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.12.3) lib/task/supervised.ex:35: Task.Supervised.reply/5
```

**Comment by DmytroNazarenko** [comment]
Related to #38
